name: flutter_lens
description: A local, in-app network inspector for Flutter test and release builds.
version: 0.1.0
homepage: https://github.com/flutter-lens/flutter_lens

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  dio: ^5.11.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
